// Sidebar is generated from the docs/ folder structure.
// Category labels, order and icons come from each folder's _category_.json.
export default {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};
